### ISSUE TITLE
TA comment: 使用案例圖

### ISSUE THREAD

**Issue by jo-ym** [karasu10250/BaseProject-Cpp#1]
1. 請確認箭頭意義（-10）
2. “設置設備”是設置討論吧？（-5）
3. “分析”需求不可能不與所有actor沒有關係（-10）

*若有修改，請在此issue下回覆，否則不予修改及加分。

**Comment by IECSD0611057** [comment]
11.30已更正(並刪除原始版本)
請查看^^

**Comment by jo-ym** [comment]
> 11.30已更正(並刪除原始版本)
> 請查看^^

OK 已修改 ilearn 上分數
